

name: pinyinizer
description: Transmform a string with numerical tone to a string with proper tone diacritics.
version: 1.0.2
homepage: https://github.com/fdematos/pinyinizer

environment:
  sdk: ">=1.19.0 <3.0.0"

dev_dependencies:
  test: '>=1.15.0 <2.0.0'