

name: pinyinizer
description: Chinese character conversion pinyin library.Accurate and complete Chinese character dictionary.Fast conversion.
version: 1.0.0
author: fdematos
homepage: https://github.com/fdematos/pinyinizer

environment:
  sdk: ">=1.19.0 <3.0.0"

dev_dependencies:
  test: '>=1.15.0 <2.0.0'